<a href="https://colab.research.google.com/github/pshkrh/food-hazard-detection/blob/initial_noval_approach/noval_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Install Dependencies


In [1]:
%%capture

!pip install numpy torch pandas scikit-learn crepes transformers tqdm

!wget https://raw.githubusercontent.com/food-hazard-detection-semeval-2025/food-hazard-detection-semeval-2025.github.io/refs/heads/main/data/incidents_train.csv

In [2]:
import pandas as pd
import numpy as np

data = pd.read_csv('incidents_train.csv', index_col=0)
data.sample()

year  month  day country  \
4094  2020      2   19      us   

                                                  title  \
4094  Saratoga Potato Chips, LLC Issues Allergy Aler...   

                                                   text hazard-category  \
4094  Saratoga Potato Chips, llc of Fort Wayne, Indi...       allergens   

                product-category                     hazard       product  
4094  prepared dishes and snacks  milk and products thereof  potato chips

# Data Preparation


In [3]:
X = data['title']
y = data[['hazard-category', 'product-category']]

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_dev, y_train, y_dev = {}, {}, {}, {}

# create train and development sets:
for column in y.columns:
    X_train[column], X_dev[column], y_train[column], y_dev[column] = train_test_split(X.values, y[column].values, test_size=.2, shuffle=True, random_state=42, stratify=y[column])
    print(column.upper())
    print('  Size of development set:', X_dev[column].shape)
    print('  Size of train set:      ', X_train[column].shape)

HAZARD-CATEGORY
  Size of development set: (1017,)
  Size of train set:       (4065,)
PRODUCT-CATEGORY
  Size of development set: (1017,)
  Size of train set:       (4065,)


# Train Base Classifier

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer().fit(X)

phi = lambda x: tfidf.transform(x).toarray()
list(tfidf.vocabulary_.keys())[:5]

['recall', 'notification', 'fsis', '024', '94']

In [6]:
category2label = {column:np.unique(y[column]) for column in y.columns}
label2id = {column:{l:i for i, l in enumerate(category2label[column])} for column in y.columns}

# show label-id mapping:
label2id['hazard-category']

{'allergens': 0,
 'biological': 1,
 'chemical': 2,
 'food additives and flavourings': 3,
 'foreign bodies': 4,
 'fraud': 5,
 'migration': 6,
 'organoleptic aspects': 7,
 'other hazard': 8,
 'packaging defect': 9}

In [7]:
from crepes import WrapClassifier
from sklearn.linear_model import LogisticRegression

# create a conformal base classifiers based on Logistic Regression:
base_classifiers = {column:WrapClassifier(LogisticRegression()) for column in y.columns}

for column in base_classifiers:
    # train the base classifier:
    base_classifiers[column].fit(
        phi(X_train[column]),
        [label2id[column][l] for l in y_train[column]]
    )

    # calibrate the base classifier:
    base_classifiers[column].calibrate(
        phi(X_dev[column]),
        [label2id[column][l] for l in y_dev[column]],
        class_cond=True
    )

Instantiate Llama

In [8]:
import getpass
from huggingface_hub import login
login(getpass.getpass('Enter your huggingface API-key:'))

Enter your huggingface API-key:··········
The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: fineGrained).
Your token has been saved to /root/.cache/huggingface/token
Login successful


In [10]:
import transformers
import torch

# create llm pipeline:
llm = transformers.pipeline(
    "text-generation",
    model="meta-llama/Meta-Llama-3.1-8B-Instruct",
    model_kwargs={"torch_dtype": torch.bfloat16},
    device_map="auto"
)

# Get special tokens for later:
bos_token_id = llm.tokenizer.convert_tokens_to_ids('<|begin_of_text|>')
eos_token_id = llm.tokenizer.convert_tokens_to_ids('<|eot_id|>')
pad_token_id = llm.tokenizer.convert_tokens_to_ids('<|eot_id|>')

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

CICLe

In [15]:
from sklearn.metrics import pairwise_distances

def get_few_shot_examples(column, text, examples_per_class=2):
    examples = []

    # we take [0] because phi([text]) returns a 2d array
    prediction_set = category2label[column][base_classifiers[column].predict_set(phi([text])).astype(bool)[0]]

    for y in prediction_set:
        texts = X_train[column][y_train[column] == y]

        embeddings = phi([text] + texts.tolist())

        similarity = (1. - pairwise_distances(embeddings, metric='cosine'))[1:,0]

        for j in np.argsort(similarity)[::-1][:examples_per_class]:
            examples.append((texts[j], y, similarity[j]))

    examples.sort(key=lambda e: e[2], reverse=True)

    return examples

samples = get_few_shot_examples('hazard-category', X_dev['hazard-category'][0])
samples

[ True False  True  True  True  True  True  True  True  True]
WrapClassifier(learner=LogisticRegression(), calibrated=True, predictor=ConformalClassifier(fitted=True, mondrian=True))
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1 0 1 1 1 1 0 1 1 1]]
---------------------


[('Woolworths Limited—Homebrand Corn & Chicken flavour noodles',
  'chemical',
  0.26776208239415844),
 ('Yours Truly Chocolates — Bondi Protein Co Vegan Protein Bar 60g, Chocolate Flavour and Salted Caramel Flavour',
  'allergens',
  0.2245709473203733),
 ('Goldroast brand Instant Nutritious Cereal\xa0–\xa0Original Flavour recalled due to undeclared milk',
  'allergens',
  0.20859555979642863),
 ('CTC Australia — Lolly Co Jersey Caramel 150g Big Lolly Jersey Caramel 160g & Fine Time Jersey Caramel 1Kg',
  'foreign bodies',
  0.16639771657798996),
 ('Corn Maiden Foods, Inc. Recalls Ready-to-Eat Beef Products Due To Misbranding',
  'fraud',
  0.13807716008333049),
 ('Ottovo International Trading Pty Ltd — Jelly With Lactic Acid (Mango & Strawberry) & Jelly (Mango Flavour & Egg Flavour)',
  'food additives and flavourings',
  0.1367338897809245),
 ('Koh-kae—Peanuts coconut cream flavour', 'chemical', 0.12898436388441925),
 ('Beehive brand Corn Syrup recalled due to pieces of plastic',
  

In [17]:
def create_prompt(column, text, examples):
    replace_qm = lambda s: s.replace('"', "'")

    context = f'We are looking for food {column.split("-")[0]}s in texts. Here are some labeled examples sorted from most probable to least probable:\n'

    for x, y, _ in examples:
        context += f'\n"{replace_qm(x)}" => {y}'

    return {"role": "user", "content": f'{context}\n\nPlease predict the correct class for the following sample. Only provide the class label.\n\n"{replace_qm(text)}" => '}

print(create_prompt('hazard-category', X_dev['hazard-category'][0], samples)["content"])

We are looking for food hazards in texts. Here are some labeled examples sorted from most probable to least probable:

"Woolworths Limited—Homebrand Corn & Chicken flavour noodles" => chemical
"Yours Truly Chocolates — Bondi Protein Co Vegan Protein Bar 60g, Chocolate Flavour and Salted Caramel Flavour" => allergens
"Goldroast brand Instant Nutritious Cereal – Original Flavour recalled due to undeclared milk" => allergens
"CTC Australia — Lolly Co Jersey Caramel 150g Big Lolly Jersey Caramel 160g & Fine Time Jersey Caramel 1Kg" => foreign bodies
"Corn Maiden Foods, Inc. Recalls Ready-to-Eat Beef Products Due To Misbranding" => fraud
"Ottovo International Trading Pty Ltd — Jelly With Lactic Acid (Mango & Strawberry) & Jelly (Mango Flavour & Egg Flavour)" => food additives and flavourings
"Koh-kae—Peanuts coconut cream flavour" => chemical
"Beehive brand Corn Syrup recalled due to pieces of plastic" => foreign bodies
"No Name brand Popping Corn recalled due to presence of insects" => oth

# Test Set Prediction

In [18]:
# download test set (conception phase, unlabelled):
!wget https://codalab.lisn.upsaclay.fr/my/datasets/download/26c12bc0-3878-4edf-8b4a-9682763c0b7e
!unzip -o 26c12bc0-3878-4edf-8b4a-9682763c0b7e
!rm 26c12bc0-3878-4edf-8b4a-9682763c0b7e

data_test = pd.read_csv('incidents.csv', index_col=0)
X_test = data_test['title'].values

data_test.sample()

--2024-11-12 01:30:48--  https://codalab.lisn.upsaclay.fr/my/datasets/download/26c12bc0-3878-4edf-8b4a-9682763c0b7e
Resolving codalab.lisn.upsaclay.fr (codalab.lisn.upsaclay.fr)... 129.175.8.8
Connecting to codalab.lisn.upsaclay.fr (codalab.lisn.upsaclay.fr)|129.175.8.8|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://miniodis-rproxy.lisn.upsaclay.fr/py3-private/public_data/ee902c30-cff6-4bc0-9525-f6a7531ddeaa/competition/19955/1/data/public_dat.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=EASNOMJFX9QFW4QIY4SL%2F20241112%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241112T013049Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=9d8b7533029950028750dfedf2b8aa3012cb04e955f6d29aa710621e5041368f [following]
--2024-11-12 01:30:49--  https://miniodis-rproxy.lisn.upsaclay.fr/py3-private/public_data/ee902c30-cff6-4bc0-9525-f6a7531ddeaa/competition/19955/1/data/public_dat.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=EASNOMJFX9Q

year  month  day country  \
413  2019     11   17      ca   

                                                 title  \
413  Farm Boy brand cheese balls recalled due to Li...   

                                                  text  
413  Food Recall Warning - Farm Boy brand cheese ba...

In [ ]:
from tqdm.notebook import tqdm

# predict test set:
for column in base_classifiers:
    # add new column to dataframe:
    data_test[column] = ['']*len(data_test)
    mask = data_test.columns == column

    for i, x in enumerate(tqdm(X_test, desc='Assessing texts')):
        # get 2 most similar texts in the training data:
        examples = get_few_shot_examples(column, x)

        if len(examples) > 1:
            # create prompt:
            prompt = create_prompt(column, x, examples)

            # prompt LLM:
            data_test.iloc[i, mask] = llm([prompt],
                bos_token_id=bos_token_id,
                eos_token_id=eos_token_id,
                pad_token_id=pad_token_id,
                max_new_tokens=32,
                do_sample=False,
                temperature=None,
                top_p=None
            )[0]["generated_text"][-1]["content"]

        else: data_test.iloc[i, mask] = examples[0]

data_test.sample()

# Save Predictions

In [ ]:
import os
from shutil import make_archive

# save predictions to a new folder:
os.makedirs('./submission/', exist_ok=True)
data_test[['hazard-category', 'product-category']].to_csv('./submission/submission.csv')

# zip the folder (zipfile can be directly uploaded to codalab):
make_archive('./submission', 'zip', './submission')